name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s . -p "test_*.py"

    - name: Package project
      run: |
        mkdir -p package
        cp calcula_imc.py package/
        cp test_calcula_imc.py package/
        # Add any other files needed for the package

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: calculadora-package
        path: package/
