name: Aplicação Python

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar testes
      run: |
        python -m unittest discover -s . -p "test_*.py"

    - name: Empacotar projeto
      run: |
        mkdir -p package
        cp calcula_imc.py package/
        cp test_calcula_imc.py package/
        # Adicione quaisquer outros arquivos necessários para o pacote

    - name: Fazer upload do artefato
      uses: actions/upload-artifact@v3
      with:
        name: calculadora-package
        path: package/